[[redirects]]
  from = "/addressService/*"
<<<<<<< HEAD
  to = "http://139.180.147.199:8082/:splat"
=======
  to = "http://139.180.147.199:8081/:splat"
>>>>>>> 07c61fd (fix netlify)
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/accountService/*"
<<<<<<< HEAD
  to = "http://139.180.147.199:8080/:splat"
=======
  to = "http://139.180.147.199:8100/:splat"
>>>>>>> 07c61fd (fix netlify)
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/coinPriceService/*"
<<<<<<< HEAD
  to = "http://139.180.147.199:8081/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
=======
  to = "http://139.180.147.199:8000/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
>>>>>>> 07c61fd (fix netlify)
