[[redirects]]
  from = "/addressService/*"
  to = "http://139.180.147.199:8082/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/accountService/*"
  to = "https://cfdf-118-70-117-216.ap.ngrok.io/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/coinPriceService/*"
  to = "http://139.180.147.199:8081/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200