// connections
export const LOADING_IMPORT_CONNECTION = 'LOADING_IMPORT_CONNECTION'
export const SUCCESS_IMPORT_CONNECTION = 'SUCCESS_IMPORT_CONNECTION'
export const FAILED_IMPORT_CONNECTION = 'FAILED_IMPORT_CONNECTION'
// export const LOADING_GET_ALL_HOLDING_BTC = 'LOADING_GET_ALL_HOLDING_BTC'
// export const SUCCESS_GET_ALL_HOLDING_BTC = 'SUCCESS_GET_ALL_HOLDING_BTC'
// export const FAILED_GET_ALL_HOLDING_BTC = 'FAILED_GET_ALL_HOLDING_BTC'
export const LOADING_DELETE_CONNECTION = 'LOADING_DELETE_CONNECTION'
export const SUCCESS_DELETE_CONNECTION = 'SUCCESS_DELETE_CONNECTION'
export const FAILED_DELETE_CONNECTION = 'FAILED_DELETE_CONNECTION'
export const LOADING_UPDATE_CONNECTION = 'LOADING_UPDATE_CONNECTION'
export const SUCCESS_UPDATE_CONNECTION = 'SUCCESS_UPDATE_CONNECTION'
export const FAILED_UPDATE_CONNECTION = 'FAILED_UPDATE_CONNECTION'

// import connection evm
export const LOADING_IMPORT_CONNECTION_EVM = 'LOADING_IMPORT_CONNECTION_EVM'
export const SUCCESS_IMPORT_CONNECTION_EVM = 'SUCCESS_IMPORT_CONNECTION_EVM'
export const FAILED_IMPORT_CONNECTION_EVM = 'FAILED_IMPORT_CONNECTION_EVM'
export const LOADING_DELETE_CONNECTION_EVM = 'LOADING_DELETE_CONNECTION_EVM'
export const SUCCESS_DELETE_CONNECTION_EVM = 'SUCCESS_DELETE_CONNECTION_EVM'
export const FAILED_DELETE_CONNECTION_EVM = 'FAILED_DELETE_CONNECTION_EVM'
// export const LOADING_UPDATE_CONNECTION_EVM = 'LOADING_UPDATE_CONNECTION_EVM'
// export const SUCCESS_UPDATE_CONNECTION_EVM = 'SUCCESS_UPDATE_CONNECTION_EVM'
// export const FAILED_UPDATE_CONNECTION_EVM = 'FAILED_UPDATE_CONNECTION_EVM'

// import connection nft
export const LOADING_IMPORT_CONNECTION_NFT = 'LOADING_IMPORT_CONNECTION_NFT'
export const SUCCESS_IMPORT_CONNECTION_NFT = 'SUCCESS_IMPORT_CONNECTION_NFT'
export const FAILED_IMPORT_CONNECTION_NFT = 'FAILED_IMPORT_CONNECTION_NFT'
export const LOADING_GET_ALL_TRANSACTION_NFT = 'LOADING_GET_ALL_TRANSACTION_NFT'
export const SUCCESS_GET_ALL_TRANSACTION_NFT = 'SUCCESS_GET_ALL_TRANSACTION_NFT'
export const FAILED_GET_ALL_TRANSACTION_NFT = 'FAILED_GET_ALL_TRANSACTION_NFT'
export const LOADING_DELETE_CONNECTION_NFT = 'LOADING_DELETE_CONNECTION_NFT'
export const SUCCESS_DELETE_CONNECTION_NFT = 'SUCCESS_DELETE_CONNECTION_NFT'
export const FAILED_DELETE_CONNECTION_NFT = 'FAILED_DELETE_CONNECTION_NFT'

// get list coin
export const LOADING_GET_LIST_COIN = 'LOADING_GET_LIST_COIN'
export const SUCCESS_GET_LIST_COIN = 'SUCCESS_GET_LIST_COIN'
export const FAILED_GET_LIST_COIN = 'FAILED_GET_LIST_COIN'

// get coin price
export const LOADING_GET_COIN_PRICE = 'LOADING_GET_COIN_PRICE'
export const SUCCESS_GET_COIN_PRICE = 'SUCCESS_GET_COIN_PRICE'
export const FAILED_GET_COIN_PRICE = 'FAILED_GET_COIN_PRICE'
