export const WAITING_CONNECT = 'WAITING_CONNECT'
export const SUCCESS_CONNECT = 'SUCCESS_CONNECT'
export const PORTFOLIO_CONNECT = 'PORTFOLIO_CONNECT'

export const EXCHANGE = 1 / 100000000
export const BILIION = 1 / 1000000000
